name: Wijzigingsverzoek
description: Indienen wijzigingsverzoek
title: "[Wijzingsverzoek]: "
labels: ["Wens"]
body:
  - type: markdown
    attributes: 
      value: |
        Bedankt voor het indienen van een wijzigingsverzoek. Beschrijf zo duidelijk mogelijk wat het wijzigingsverzoek inhoudt.
        Voordat je aan de slag gaat met dit formulier, nog een puntje:
        Heeft iemand anders al eens een soortgelijk issue ingediend? Check dit in de [backlog](https://github.com/Geonovum/IMGeo-dev/issues).
  - type: input
    id: name
    attributes: 
      label: Uw naam
    validations:
      required: false
  - type: input
    id: contact
    attributes: 
      label: Contactdetails
      description: Hoe kunnen we contact met je opnemen als er nog vragen zijn?
      placeholder: bijv. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: browsers
    attributes:
      label: Welke rol heeft u?
      options:
        - label: Bronhouder (of koepel van bronhouders)
        - label: Afnemer/gebruiker
        - label: Verstrekker
        - label: Leverancier
        - label: Standaarden beheerder
        - label: Besluitvormend orgaan
	- label: Toezichthouder
	- label: Beleidsverantwoordelijke
        - label: Niet van toepassing / Anders
  - type: dropdown
    id: application
    attributes:
      label: Voor welk onderdeel wil je een wijzigingsverzoek indienen?
      options:
        - Het informatiemodel: domeinwaardes en objecten
        - Het informatiemodel: GML en XSD schema's
        - Het informatiemodel: geometriewijzigingen
        - Objectenhandboek
        - Visualisatie
        - Berichtenverkeer
	- Anders
    validations:
      required: true
  - type: textarea
    id: description
    attributes: 
      label: Omschrijving wijzigingsverzoek (wat?)
      description: Wat is de voorgestelde wijziging?
    validations:
      required: true
  - type: textarea
    id: description
    attributes: 
      label: Omschrijving wijzigingsverzoek (waarom?)
      description: Waarom stelt u deze wijziging voor?
    validations:
      required: true 
   - type: textarea
    id: description
    attributes: 
      label: Omschrijving wijzigingsverzoek (voor wie/wat?)
      description: Wat wordt hiermee opgelost of wie wordt hier mee geholpen?
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes: 
      label: Opmerkingen
      description: Heeft u nog andere opmerkingen of iets wat u wilt delen met ons, laat dat hier achter.
    validations:
      required: false
  - type: markdown
    attributes: 
      value: |
        Alvast bedankt voor het indienen, we gaan er zsm mee aan de slag.
        Geonovum
